### ISSUE TITLE
MT7601 Request

### ISSUE THREAD

**Issue by qiuzhu** [chris1111/TP-LINK-WIFI-Network-macOS#1]
is it possible to support the MT7601? my usb wifi card chip is MT7601, after I install this app , wifi does not work

**Comment by chris1111** [comment]
Edit**
For High Sierra?
Try this kext, install with kext Wizzard and repair  the correct permission also rebuild kext cache 
with Terminal . then Reboot
[RT2870USBWirelessDriver.kext.zip](https://github.com/chris1111/TP-LINK-WIFI-Network-macOS/files/1811771/RT2870USBWirelessDriver.kext.zip)

Let me know if its work I ad support in the programme for MT7601

**Comment by qiuzhu** [comment]
It seems not work , after I install it . there is no wifi at all
this is my wifi card usb information: 

```
 产品 ID：	0x760c
  厂商 ID：	0x0e8d  (MediaTek Inc.)
  版本：	0.01
  序列号：	1.0
  速度：	最大 480 Mb/秒
  制造商：	MediaTek
  位置 ID：	0x00200000 / 1
  可用电流 (mA)：	500
  所需电流 (mA)：	160
  额外的操作电流 (mA)：	0
```

and In  extension, the kext is applyed

**Comment by chris1111** [comment]
I dont know what whats wrong here ? Sorry
I closed issue
