### ISSUE TITLE
TP-LINK TL-WN823N v2 doesn't run

### ISSUE THREAD

**Issue by adzodamelk** [chris1111/TP-LINK-WIFI-Network-macOS#4]
Hello chris,

I've tried to use TP-LINK-WIFI-Network-macOS package with my MacBook Air (internal wifi is broken) + Mojave + TP-LINK TL-WN823N v2 dongle based on Realtek RTL8192EU.

Unfortunately it doesn't run, probably because RTL8192EU isn't supported.... however I saw that your "Wireless-USB-Adapter-Clover" supports also RTL8192EU, but I don't know how to use it, because I'm using a "real Mac" and not an hackintosh.

Do you have any suggestion?

thanks in advance!
 adso

**Comment by chris1111** [comment]
Yes I prepare a package for real mac but you need SIP security disable to using it
Also Gatekeeper disable  
Here the package, I just test and its work good
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu313.png)


EDIT ***
remember I am not responsable anny boot failled on real Mac or Hackintosh For this software
You use it at your own risk

**Comment by adzodamelk** [comment]
Thank you so much, Chris! 

Today evening I'll test as soon as I'll be back at home.... of course I'll let you know!

**Comment by chris1111** [comment]
> Thank you so much, Chris!
> 
> Today evening I'll test as soon as I'll be back at home.... of course I'll let you know!

if its not working for you, you can try this one 


EDIT ***
remember I am not responsable anny boot failled on real Mac or Hackintosh For this software
You use it at your own risk

**Comment by chris1111** [comment]
Ok please go to this post and used the package available in the issue here 
https://github.com/chris1111/Wireless-USB-Adapter-Clover/issues/3
Issue is closed
