### ISSUE TITLE
Request: Ralink Utility in System  Prefs 

### ISSUE THREAD

**Issue by ellaosx2007** [chris1111/TP-LINK-WIFI-Network-macOS#5]
Hi Chris
can you do a package of the utility that resides in system preference instead of a window box?

Thanks

**Comment by chris1111** [comment]
> Hi Chris
> can you do a package of the utility that resides in system preference instead of a window box?
> 
> Thanks

I have already try a package but its unnecessary
You can used this panel 
[D-LinkWirelessUtility.prefPane.zip](https://github.com/chris1111/TP-LINK-WIFI-Network-macOS/files/2599876/D-LinkWirelessUtility.prefPane.zip)
Let me know if that work

**Comment by ellaosx2007** [comment]
**Sierra 10.12.6**
I will test and report back.

Thanks

**Comment by ellaosx2007** [comment]
works ok.
thanks for the attachment.
